language: python

python:
  - '3.8'

addons:
  chrome: stable

branches:
  only:
    - main

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="purbeurre.settings.travis"

services:
  - postgresql

script: pytest