dist: bionic
language: python

python:
  - '3.8'

addons:
  chrome: stable

branches:
  only:
    - main

install:
  - pip install pipenv pytest
  - pipenv install --dev
  - python manage.py migrate
  - python manage.py db_insertion

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script: pytest