# Generated by Django 3.2.4 on 2021-07-08 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_to_substitute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_as_product', to='products.product')),
                ('substitute_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites_as_substitute', to='products.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
