# Generated by Django 3.2.4 on 2021-06-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('nutriscore', models.CharField(max_length=1)),
                ('fat_100g', models.DecimalField(decimal_places=3, max_digits=6)),
                ('satured_fat_100g', models.DecimalField(decimal_places=3, max_digits=6)),
                ('salt_100g', models.DecimalField(decimal_places=3, max_digits=6)),
                ('suger_100g', models.DecimalField(decimal_places=3, max_digits=6)),
                ('category', models.ManyToManyField(help_text='Select a category for this product', to='products.Category')),
            ],
        ),
    ]
