# Generated by Django 3.2.8 on 2021-10-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', to='products.Category'),
        ),
    ]
