# Generated by Django 3.2.8 on 2021-10-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', to='products.Keywords'),
        ),
    ]
